In [161]:
import numpy as np
from numpy import linalg
import sympy as sm
import warnings
warnings.simplefilter("ignore")

## Example 1
### 2.4.b) Compute the following matrix products

In [162]:
"""
- declare 2 matrices and perform multiplication using Numpy 

"""

A =       [[1,2,3],
           [4,5,6],
           [7,8,9]]

B =       [[1,1,0],
           [0,1,1],
           [1,0,1]]

C = np.dot(A,B)
print('Product of 2 matrices:')
print('----------------------')

print(C)

Product of 2 matrices:
----------------------
[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


### Optional: definition of matrix with zeros and ones 

In [163]:

zero_matrix = np.zeros((3,3))
ones_matrix = np.ones((3,3))

print('Matrix of zeros:')
print('----------------')
print(zero_matrix)
print('\n')

print('Matrix of ones:')
print('---------------')
print(ones_matrix)

Matrix of zeros:
----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Matrix of ones:
---------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Example 2
### 2.5.a) Find the set S of all solutions in x of the following inhomogeneous linear system $Ax = b$.

> The linear system Ax = b is called *homogeneous* if b = 0; otherwise, it is called *inhomogeneous*.

In [164]:
A = np.array([[1,1,-1,-1],
             [2,5,-7,-5],
             [2,-1,1,-3],
             [5,2,-4,2]])

b = np.array([1, -2, 4, 6])  

### Question 1: is matrix A invertible? 

In [165]:
if(linalg.det(A) !=0):
    print('Matrix A is invertible.')
else: 
    ('Matrix is not invertible.')
print('\n')
print('Determinant of A is:')
print(linalg.det(A))

Matrix A is invertible.


Determinant of A is:
-72.00000000000007


### Question 2: is matrix A squared? 

In [166]:
print(A.shape)

(4, 4)


### Question 3: are columns of matrix A linearly independent? 

In [167]:
rf, inds = sm.Matrix(A).rref()
print('Reduced row echelon form of A is:')
rf

Reduced row echelon form of A is:


Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [168]:
print('Pivot columns are: ')
print('\n')
print(inds)

Pivot columns are: 


(0, 1, 2, 3)


### Approach 1: using $x = {A}^{-1}b$ 

### Solve manually 

In [169]:
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print('Manual solution is:')
print(x)

Manual solution is:
[1.77777778 0.13888889 0.83333333 0.08333333]


### Linalg implementation

> $a$ must be square and of full-rank, i.e., all rows (or, equivalently, columns) must be linearly independent; if either is not true, use `lstsq` for the least-squares best “solution” of the system/equation.

In [170]:
x = np.linalg.solve(A, b)
print('Linalg solution is:')
print(x)

Linalg solution is:
[1.77777778 0.13888889 0.83333333 0.08333333]


### Approach 2: using least-squares  (Moore-Penrose pseudo-inverse)

$Ax = b$ <br>
$x = {(A^TA)}^{-1}A^Tb$

In [171]:
A_inv = np.linalg.inv(A)
A_T = np.transpose(A)
p_inv = np.dot(np.linalg.inv(np.dot(A_T, A)), 
               A_T)

In [172]:
x = np.dot(p_inv, b)
print(x)

[1.77777778 0.13888889 0.83333333 0.08333333]


## Example 3
### 2.6.a) Using Gaussian approach, find all solutions to the following inhomogeneous linear system $Ax = b$.

In [183]:
A = np.array([[0,1,0,0,1,0],
              [0,0,0,1,1,0],
              [0,1,0,0,0,1],
             ])

# note, here one dimension was added
b = np.array([[2,-1,1]])

> Note, that matrix is **not square** and **non-invertible**.  <br>
`np.linalg.solve` needs a full-rank square matrix.

### Special solution to $Ax = b$

In [174]:
A_b = np.concatenate((A, b.T), axis=1)

In [175]:
rf, inds = sm.Matrix(A_b).rref()
print('Reduced row echelon form of (A b) is:')
rf

Reduced row echelon form of (A b) is:


Matrix([
[0, 1, 0, 0, 0,  1,  1],
[0, 0, 0, 1, 0,  1, -2],
[0, 0, 0, 0, 1, -1,  1]])

In [176]:
print('Pivot columns of (A b) are: ')
print('\n')
print(inds)

Pivot columns of (A b) are: 


(1, 3, 4)


In [177]:
rf_0, inds_0 = sm.Matrix(A).rref()
print('Reduced row echelon form of A is:')
rf_0

Reduced row echelon form of A is:


Matrix([
[0, 1, 0, 0, 0,  1],
[0, 0, 0, 1, 0,  1],
[0, 0, 0, 0, 1, -1]])

General solution will be: <br>
$$\begin{bmatrix} 0 \\ 1 \\ 0 \\ -2 \\ 1 \\ 0 \end{bmatrix} = c_1 \begin{bmatrix} 0 \\ -1 \\ 0 \\ 1 \\ 1 \\ 1 \end{bmatrix} $$ 

### References

1. Mathematics for Machine Learning: https://mml-book.github.io/<br>
2. Source for `linalg`: https://riptutorial.com/numpy/example/16034/find-the-least-squares-solution-to-a-linear-system-with-np-linalg-lstsq<br>
3. Algorithmic approach to Gaussian elemenation: https://martin-thoma.com/solving-linear-equations-with-gaussian-elimination/